[project]
name = "next-starter-template"
version = "0.1.0"
description = "Excel generator for tile grids (Cloudflare Python Worker)"
requires-python = ">=3.12"
dependencies = ["openpyxl==3.1.5"]

[dependency-groups]
dev = ["workers-py"]